# Generated by Django 3.0.8 on 2020-07-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200705_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='links',
        ),
        migrations.AddField(
            model_name='article',
            name='links',
            field=models.ManyToManyField(blank=True, null=True, related_name='_article_links_+', to='articles.Article'),
        ),
    ]
