# Generated by Django 3.0.8 on 2020-07-05 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200705_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='links',
        ),
        migrations.AddField(
            model_name='article',
            name='links',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Article'),
        ),
    ]
