# Generated by Django 3.0.8 on 2020-07-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200705_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='_article_links_+', to='articles.Article'),
        ),
    ]
